apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-web
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: sealed-secrets-web
    app.kubernetes.io/instance: sealed-secrets-web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP